os: linux
dist: focal
language: go
go:
    - "1.14"
before_script:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
script:
    - go test -timeout 30s -v -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -service=travis-pro -repotoken $COVERALLS_TOKEN